### ISSUE TITLE
FEATURE: Collision detection

### ISSUE THREAD

**Issue by flexdinesh** [Noviny/emoji-uid#5]
Might want to add collision detection to make sure no two ids are same.

Eg: 

```js
const id = eid(1)

// If eid(1) is invoked a 100 times
// there's a good probability to receive the same id
// more than once.
```

_Solution: Could store a local cache of all generated ids to retry when there's a collision._

**Comment by Noviny** [comment]
Thanks for the issue! I'd worry that this adds a lot of complexity to give a sense of safety, without actually granting safety (as this only works within the same process)

I'd argue that at `eid(1)` you just never have a guarantee of uniqueness, and even at 3👀, this library is far far less safe than something like uuid for generating ids.

**Comment by flexdinesh** [comment]
Love the idea tho. Probably will make heavy use of this in codesandbox demos 🎉
